### ISSUE TITLE
Server issue

### ISSUE THREAD

**Issue by Santana1053** [YahnisElsts/wp-update-server#44]
If I go to the download link in my browser, it downloads it fine, but using cURL, I get the following error
>   <h1>400 Bad Request</h1> <p>You must specify a package slug.</p>

Wordpress reports the download link as 'malformed'

request.log shows `GET 	download	-	-	-	-	action=download`

Even though it has the slug in the URL. If I put the slug first and the action secion, the request log would show the slug and no action

**Comment by YahnisElsts** [comment]
Could you please post the actual URL? Also, are you running the latest version (master branch) or an older release?

**Comment by Santana1053** [comment]
I am using the latest release version. URL is https://dl.maudience.com//?action=download&slug=maudience

**Comment by YahnisElsts** [comment]
I think I see what the problem is - there are two slashes after the domain name instead of one. This is a known bug that was fixed about a week ago. Try the master branch.

**Comment by Santana1053** [comment]
If I replace the .com//? with .com/? or even just .com? I still get the same issue. I will try the master branch though

**Comment by Santana1053** [comment]
The issue is still occurring for me with the master branch

**Comment by YahnisElsts** [comment]
Did the download URL change when you updated the code? If not, the old plugin metadata might still be cached somewhere. Try deleting everything in the "cache" subdirectory and click the "check for updates" to force a new check.

> If I replace the .com//? with .com/? or even just .com? I still get the same issue. 

That's with cURL, right? I tried it with http://onlinecurl.com/ and got a 404 instead of a 400. I assume you've removed the package to people who stumble upon this thread from downloading it.

**Comment by Santana1053** [comment]
Try now, it was returning a 404 because I changed the owner of the package folder, and the server didn't have permission to read the packages, but it should be fixed now.
Now the download link is https://dl.maudience.com/?action=download&slug=maudience

**Comment by Santana1053** [comment]
Wordpress is now updating from the URL

**Comment by YahnisElsts** [comment]
Well, that's still a 404 for me, but I'm glad to hear it's fixed on your end :+1:
